### ISSUE TITLE
_DAY_NAMES definition seems not correct

### ISSUE THREAD

**Issue by YinHu1985** [verillious/godot-datetime#4]
It starts with a "" and end with "sunday"

But according to comments and the weekday logic, the first one should be "sunday"

**Comment by verillious** [comment]
I think this is due to the built in `OS.get_datetime_from_unix_time` returning `weekday` as an int ranging from 1-7, so it's easier to simply set the index 0 to empty - I do the same thing for `_MONTH_NAMES` and `_DAYS_IN_MONTH` - have you been seeing an issue in your project? If so what version of Godot are you using?

**Comment by verillious** [comment]
Closing for now @YinHu1985 Feel free to open another issue if you're seeing problems in your project

**Comment by YinHu1985** [comment]
According to the code, I think Time.get_unix_time_from_datetime_dict is used here and there
and according to 
https://docs.godotengine.org/en/stable/classes/class_time.html#methods
The Weekday enum is 0-6

Easy to reproduce: just keep add_days(1) and check the weekday_name field

**Comment by verillious** [comment]
Ah - maybe this changed from Godot 3 to Godot 4. I'll take a look and push a patch for the 4.0 version later today. Thanks @YinHu1985

**Comment by verillious** [comment]
@YinHu1985 This is now fixed in 1.0.2 (Godot 4)
